# Generated by Django 3.0.5 on 2020-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='priyanshu', max_length=255),
            preserve_default=False,
        ),
    ]
